export const USER_LOGGED = 'USER_LOGGED';
export const FORGOT_PASSWORD_MOBILENUMBER = 'FORGOT_PASSWORD_MOBILENUMBER';
export const COUNTRY_DETAILS = 'COUNTRY_DETAILS';
export const CURRENT_USER = 'CURRENT_USER'